name: Advanced pack
description: "Advanced pack"
 
inputs:
  working_directory:
    required: true
    description: "The working directory"
  project_directory:
    required: true
    description: "The project directory. Supported formats: './Path' | 'Path'"
  nuget_name:
    required: true
    description: "The expected package name of the package"
  nuget_version:
    required: false
    default: ""
    description: "The expected package version of the package"
  configuration:
    description: "Build configuration. DEBUG | RELEASE | .."
    required: true
  output_path:
    description: "Output path. For example: ./PROJECT_NAME/package"
    required: true
  nuget_pack_options:
    description: "The options for nuget pack. The default: -Symbols -SymbolPackageFormat 'snupkg'"
    required: false
    default: "-Symbols -SymbolPackageFormat snupkg"
 
runs:
  using: composite
  steps:
    - name: Use NuGet 6.7.x
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '6.7.x'
 
      # create a package a default pack configuration
      # unfortunately, such approach doesn't allow specififying custom package metadata like name and description, so proceed with next steps
    - name: Regular pack
      shell: bash
      run: |
        echo "================================== Regular pack ========================================"
        cd ${{ inputs.working_directory }}
        version=${{ inputs.nuget_version }}
        echo "Starting default pack.."

        if [ $version ]; then
          output=$(nuget pack ${{ inputs.project_directory }} -Build -IncludeReferencedProjects -Version $version -Properties Configuration=${{ inputs.configuration }} -OutputDirectory ${{ inputs.output_path }} ${{ inputs.nuget_pack_options }})
        else
          output=$(nuget pack ${{ inputs.project_directory }} -Build -IncludeReferencedProjects -Properties Configuration=${{ inputs.configuration }} -OutputDirectory ${{ inputs.output_path }} ${{ inputs.nuget_pack_options }})
        fi
        package_path=$(echo "$output" \
          | grep "Successfully created package" \
          | head -n 1 \
          | sed -E "s/.*Successfully created package '(.*)'.*/\1/")
        package_file_name="$(basename "$(basename "$package_path")" .nupkg)"
        echo "package_file_name: $package_file_name"
        echo "created_package_name=${package_file_name}" >> $GITHUB_ENV
 
      # unzip previously create .nupkg file and get nuspec file from there. Copy this file to the project directory
    - name: Get and copy nuspec file
      shell: bash
      run: |
        echo "================================== Get and copy nuspec file ============================"
        artifacts=${{ inputs.output_path }}

        nuget_name=$created_package_name
        project_directory=${{ inputs.project_directory }}

        # Unzipping nupkg..
        echo "Prepare nuspec.."
        unzipped_artifacts="${artifacts}_${nuget_name}_unzipped"
        echo "Unzipped artifacts path: $unzipped_artifacts"
        cp -r $artifacts $unzipped_artifacts
        cd $unzipped_artifacts
 
        for nuget_file in "${nuget_name}"*.nupkg; do
          if [ -e "$nuget_file" ]; then
            echo "Unzipping $nuget_file..."
            unzip -o "$nuget_file" -d . 
          else
            echo "Expected nuget file: $nuget_file doesn't exist'"
            exit 1
          fi
        done
        # Unzipping has been complited
 
        echo "Nupkg for processing: $nuget_file"
        nuspec_file=$(shopt -s nullglob; files=( *.nuspec ); (( ${#files[@]} == 1 )) && echo "${files[0]}" || { echo "Error: expected exactly one .nuspec file, found ${#files[@]}" >&2; exit 1; })
        echo "Nuspec file: $nuspec_file"
        if [ ! -f $nuspec_file ]; then
          echo "Nuspec $nuspec_file has not been found"
          exit 1
        fi
        nuspec_destination=${GITHUB_WORKSPACE%/}/${project_directory#./}
        echo -e "\nNuspec destination: $nuspec_destination"
 
        # Copy nuspec file to the project directory
        cp $nuspec_file $nuspec_destination
        echo "nuspec_destination=${nuspec_destination}" >> $GITHUB_ENV
 
      # modify nuspec file
    - name: Update nuspec file using PowerShell
      shell: pwsh
      run: |
        Write-Host "================================== Update nuspec file using PowerShell ==========="
        cd ${{ inputs.working_directory }}
        # 1. Nuspec directory
        $nuspec_Destination = $env:nuspec_destination
        Write-Host "Nuspec destination: $nuspec_Destination"
 
        $nuspecFiles = Get-ChildItem -Path $nuspec_Destination -Filter *.nuspec -File
        if (!$nuspecFiles) {
            Write-Host "Nuspec file has not been found in $nuspec_Destination"
            exit 1
        }
        if ($nuspecFiles.Count -ne 1) {
            Write-Host "Nuspec file must be single."
            exit 1
        }
        $xmlPath = $nuspecFiles[0]
        if (-not (Test-Path $xmlPath)) {
            Write-Host "Error: The file path '$($xmlPath)' does not exist."
            exit 1
        }
        Write-Host "Befor modifying:"
        cat $xmlPath
        # Load the XML document
        [xml]$xmlDoc = Get-Content -Raw  $xmlPath
        $nsMgr = New-Object System.Xml.XmlNamespaceManager($xmlDoc.NameTable)
        # TODO: remove this namespace dependency since it may be various on diffrent configurations
        $nsMgr.AddNamespace("ns", "http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd")
        $nsMgr.AddNamespace("ns2", "http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd")
        # 1. Set id
        $idNode = $xmlDoc.SelectSingleNode("//ns:metadata/ns:id | //ns2:metadata/ns2:id", $nsMgr)
        if ($idNode -ne $null) {
            $idNode.InnerText = "${{ inputs.nuget_name }}"
            Write-Host "<id> has been found: $($idNode.InnerText)."
        } else {
            Write-Host "<id> node not found."
            exit 1
        }
 
        # 2. Set description as git git commit details
        $git_description=(git show --summary) -Join "`r`n"
        # Update the <description> node (supports multi-line text)
        $descriptionNode = $xmlDoc.SelectSingleNode("//ns:metadata/ns:description | //ns2:metadata/ns2:description", $nsMgr)
        if ($descriptionNode -ne $null) {
            $descriptionNode.InnerText = "Commit info: $git_description"
        } else {
            Write-Host "<description> node not found."
            exit 1
        }
        $xmlDoc.Save($xmlPath)
        cat $xmlPath
 
      # run nuget pack again but based on the newly configured nuspec
    - name: Custom pack
      shell: bash
      run: |
        echo "================================== Custom pack ========================================="
        cd ${{ inputs.working_directory }}
        project_directory=${{ inputs.project_directory }}
        if ! ls $project_directory/*.nuspec >/dev/null 2>&1; then
          echo "Error: Nuspec file must exist in ${project_directory}" >&2
          exit 1
        fi
        version=${{ inputs.nuget_version }}
        echo "Starting custom pack.."
        if [ $version ]; then
            nuget pack ${{ inputs.project_directory }} -Build -IncludeReferencedProjects -Version $version -Properties Configuration=${{ inputs.configuration }} -OutputDirectory ${{ inputs.output_path }} ${{ inputs.nuget_pack_options }}
        else
            nuget pack ${{ inputs.project_directory }} -Build -IncludeReferencedProjects -Properties Configuration=${{ inputs.configuration }} -OutputDirectory ${{ inputs.output_path }} ${{ inputs.nuget_pack_options }}
        fi
 
      # rename extensions of the original nugets just to ignore them in further steps
    - name: Rename original packages
      shell: pwsh
      run: |
        Write-Host "================================== Rename original packages ======================"
        $nuget_name=$env:created_package_name
        Write-Host "Rename original artifacts. Nuget name: $nuget_name"
        $artifacts="${{ inputs.output_path }}"
        $desiredNugetName = "${{ inputs.nuget_name }}"
        Get-ChildItem -Path $artifacts -File | ForEach-Object {
            Write-Host "$_.Name"
            $currentBaseName = [System.IO.Path]::GetFileNameWithoutExtension($_.Name)
            if ($currentBaseName.StartsWith($nuget_name)) {
                Write-Host "#current: $currentBaseName"
                Write-Host "#current_nuget: $nuget_name"
                Write-Host "#desired: $desiredNugetName"
                $oldExtension = $_.Extension
                # Compute the new extension by appending ".orig" to the old extension
                $newExtension = "$oldExtension.orig"
 
                $newPath = [System.IO.Path]::ChangeExtension($_.FullName, $newExtension)
                Write-Host "Changing extension of '$($_.FullName)' to '$newPath'"
                Rename-Item -Path $_.FullName -NewName $newPath
            }
        }