name: Build .Net Framework

on:
  push:
    branches: [ "master" ]

  workflow_call:

  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: ./Lib.sln
  PACKAGE_PATH: ./LibTest/package
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set version environment variable
        shell: pwsh
        run: |
          $version = (Get-Date -Format "yyyy.M.d.") + [int](New-TimeSpan -Start (Get-Date).Date -End (Get-Date)).TotalSeconds
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Use the version
        run: |
          echo "Version is: ${{ env.VERSION }}"

      - name: Use the version 2
        shell: pwsh
        run: |
          echo "Version is: $env:VERSION"
